import { Link } from 'react-router-dom';
import LegalShell, { Section } from './LegalShell';

/**
 * Privacy Policy. GDPR-aware template tailored to CareerSense's actual data
 * flows. Bracketed placeholders ([...]) are operator-specific details to fill
 * in before publishing (legal name, address, contact email, jurisdiction).
 */
const Privacy = () => (
  <LegalShell title="Privacy Policy" lastUpdated="12 June 2026">
    <Section heading="Who we are">
      <p>
        CareerSense ("we", "us") is an AI-assisted career-guidance service operated
        by [Your legal name / company], [Your address]. For any privacy question or
        to exercise your rights, contact us at [your-email] or via our{' '}
        <Link to="/contact" className="text-blue-600 underline">contact page</Link>.
        We are the data controller for the personal data described below.
      </p>
    </Section>

    <Section heading="What we collect">
      <p>We only collect what we need to provide the service:</p>
      <ul className="list-disc space-y-1 pl-6">
        <li>
          <strong>Your CV.</strong> When you upload a PDF or DOCX, we extract its
          text to generate your analysis. The uploaded file is processed
          transiently and removed shortly after (our servers sweep temporary
          uploads regularly); we do not retain the original file long-term.
        </li>
        <li>
          <strong>Account data.</strong> If you create an account, our
          authentication provider (Clerk) stores your email, name, and login
          credentials. We reference you by an account identifier.
        </li>
        <li>
          <strong>Generated content.</strong> Your analyses, discovery
          conversations, roadmaps, and progress are saved to your account so you
          can return to them.
        </li>
        <li>
          <strong>Feedback &amp; waitlist.</strong> If you send feedback, contact
          us, or join our updates list, we store the message and any email address
          you provide.
        </li>
        <li>
          <strong>Technical data.</strong> Standard server logs (e.g. IP address,
          request metadata) used for security, abuse prevention, and operating the
          service.
        </li>
      </ul>
    </Section>

    <Section heading="How we use it">
      <ul className="list-disc space-y-1 pl-6">
        <li>To produce and store your career analysis and related features.</li>
        <li>To operate, secure, and improve the service.</li>
        <li>To respond to your messages and, if you opt in, send you updates.</li>
      </ul>
      <p>
        <strong>Legal bases (GDPR Art. 6):</strong> performing the service you
        request (contract); your consent (e.g. joining the updates list); and our
        legitimate interests in securing and improving the service. You can
        withdraw consent at any time.
      </p>
    </Section>

    <Section heading="Service providers (processors)">
      <p>
        We share data only with providers that help us run CareerSense, under
        appropriate data-protection terms:
      </p>
      <ul className="list-disc space-y-1 pl-6">
        <li><strong>OpenAI</strong> — processes your CV/conversation text to generate analysis (model: gpt-4o-mini).</li>
        <li><strong>Clerk</strong> — authentication and account management.</li>
        <li><strong>Neon</strong> — managed PostgreSQL database hosting your saved data.</li>
        <li><strong>Render</strong> — backend application hosting.</li>
        <li><strong>Vercel</strong> — frontend hosting.</li>
        <li><strong>Resend</strong> — delivery of notification emails.</li>
      </ul>
      <p>
        Some providers may process data outside the EU/EEA. Where that happens, we
        rely on appropriate safeguards (such as Standard Contractual Clauses). We
        do not sell your personal data.
      </p>
    </Section>

    <Section heading="AI processing">
      <p>
        Your analysis is generated by a third-party AI model. AI output can be
        inaccurate or incomplete and is provided for guidance only — see our{' '}
        <Link to="/terms" className="text-blue-600 underline">Terms of Service</Link>.
        We do not use your content to train third-party models beyond what is
        necessary to return your result.
      </p>
    </Section>

    <Section heading="Retention">
      <p>
        Uploaded files are deleted shortly after processing. Account data and
        generated content are kept while your account is active. Delete your
        account or contact us to have your data erased. Feedback and waitlist
        entries are kept until no longer needed for the purpose collected.
      </p>
    </Section>

    <Section heading="Your rights">
      <p>
        Under the GDPR you have the right to access, rectify, erase, restrict, or
        port your personal data, and to object to certain processing. You may also
        lodge a complaint with your local data-protection authority. To exercise
        any right, contact us at [your-email] — we will respond within the
        statutory time frame.
      </p>
    </Section>

    <Section heading="Cookies">
      <p>
        We use essential cookies needed to sign you in and keep the service
        secure (set by our authentication provider). We do not use advertising
        cookies.
      </p>
    </Section>

    <Section heading="Changes">
      <p>
        We may update this policy as the service evolves. We will revise the "last
        updated" date above and, for material changes, take reasonable steps to
        notify you.
      </p>
    </Section>
  </LegalShell>
);

export default Privacy;
