import { Link } from 'react-router-dom';
import LegalShell, { Section } from './LegalShell';

/**
 * Terms of Service. Good-faith template tailored to CareerSense. Bracketed
 * placeholders ([...]) are operator-specific details to fill in before
 * publishing (legal name, governing jurisdiction).
 */
const Terms = () => (
  <LegalShell title="Terms of Service" lastUpdated="12 June 2026">
    <Section heading="1. Acceptance">
      <p>
        By accessing or using CareerSense (the "Service"), you agree to these
        Terms. If you do not agree, please do not use the Service. The Service is
        operated by [Your legal name / company].
      </p>
    </Section>

    <Section heading="2. What the Service does">
      <p>
        CareerSense uses AI to analyze a CV you provide and generate career
        guidance — including profile insights, matching roles, resume suggestions,
        discovery conversations, and learning roadmaps.
      </p>
    </Section>

    <Section heading="3. AI output — not professional advice">
      <p>
        Guidance produced by CareerSense is generated by an automated AI model.
        It may be inaccurate, incomplete, or out of date, and it is provided for
        informational purposes only. It is <strong>not</strong> professional
        career, recruitment, legal, financial, or other advice. You are
        responsible for evaluating and verifying any output before relying on it,
        and any decisions you make based on it are your own.
      </p>
    </Section>

    <Section heading="4. Acceptable use">
      <p>You agree not to:</p>
      <ul className="list-disc space-y-1 pl-6">
        <li>Upload content you do not have the right to share, or anyone else's personal data without their permission.</li>
        <li>Use the Service unlawfully, or to harass, abuse, or harm others.</li>
        <li>Attempt to disrupt, overload, reverse-engineer, or gain unauthorized access to the Service.</li>
        <li>Use automated means to scrape or abuse the Service or circumvent rate limits.</li>
      </ul>
    </Section>

    <Section heading="5. Accounts">
      <p>
        Some features require an account, managed through our authentication
        provider. You are responsible for keeping your login secure and for
        activity under your account.
      </p>
    </Section>

    <Section heading="6. Intellectual property">
      <p>
        You retain ownership of the content you upload. You grant us a limited
        licence to process that content solely to provide the Service to you. The
        CareerSense software, branding, and design remain our property.
      </p>
    </Section>

    <Section heading="7. Privacy">
      <p>
        Our handling of personal data is described in our{' '}
        <Link to="/privacy" className="text-blue-600 underline">Privacy Policy</Link>,
        which forms part of these Terms.
      </p>
    </Section>

    <Section heading="8. No warranty">
      <p>
        The Service is provided "as is" and "as available", without warranties of
        any kind, whether express or implied, including fitness for a particular
        purpose and accuracy of results, to the fullest extent permitted by law.
      </p>
    </Section>

    <Section heading="9. Limitation of liability">
      <p>
        To the maximum extent permitted by law, we are not liable for indirect,
        incidental, or consequential damages, or for any loss arising from your
        reliance on AI-generated guidance. Nothing in these Terms limits liability
        that cannot be excluded under applicable law.
      </p>
    </Section>

    <Section heading="10. Termination">
      <p>
        You may stop using the Service at any time. We may suspend or terminate
        access if you breach these Terms or to protect the Service or its users.
      </p>
    </Section>

    <Section heading="11. Governing law">
      <p>
        These Terms are governed by the laws of [Germany / your jurisdiction],
        without regard to conflict-of-law rules. Mandatory consumer-protection
        rights in your country of residence still apply.
      </p>
    </Section>

    <Section heading="12. Changes">
      <p>
        We may update these Terms as the Service evolves. We will revise the "last
        updated" date above; continued use after changes means you accept them.
        Questions? Reach us via the{' '}
        <Link to="/contact" className="text-blue-600 underline">contact page</Link>.
      </p>
    </Section>
  </LegalShell>
);

export default Terms;
